# Generated by Django 4.0.3 on 2022-03-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(default='COD', max_length=50)),
                ('order_total', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('total_products', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Transit'), (3, 'Delivered'), (0, 'Cancelled'), (4, 'Refund Initiated'), (5, 'Refund Processed')])),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product_price', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('discounted_price', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Transit'), (3, 'Delivered'), (0, 'Cancelled'), (4, 'Refund Initiated'), (5, 'Refund Processed')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productoption')),
            ],
        ),
    ]
